name: 'Setup Score environment'
description: 'Setup Score environment and add it to the PATH'
inputs:
  file:
    description: 'The Score CLI tool to install: score-compose, score-humanitec, or score-helm.'
    required: true
  version:
    description: 'The Score version to download and use. Use "latest" to update automatically.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'